# Generated by Django 5.0.4 on 2024-05-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_tweet_user_profile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='entity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
