# Generated by Django 5.0.4 on 2024-05-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_tweet_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='person',
        ),
    ]
